version: '3.7'

services:
  main:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - chargenet
