# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # -- Label 'environment'
  environment: ""

  # -- Google Cloud - Project ID
  project_id: ""
  # -- Google Cloud - Region
  region: ""

  # -- DNS domain
  domain: ""

  # Image
  image:
    # -- Repository ID
    repository: ""
    # -- Tag; overrides the image tag whose default is the chart appVersion.
    tag: ""

# Resources
resources:
  # -- Resources - Requests
  requests:
    cpu: ""
    memory: ""
  # -- Resources - Limits
  limits:
    cpu: ""
    memory: ""

# Autoscaling
autoscaling:
  # -- Autoscaling - Minimal replicas value (Horizontal Pod Autoscaler)
  min_replicas: 1
  # -- Autoscaling - Maximum replicas value (Horizontal Pod Autoscaler)
  max_replicas: 5
  # -- Autoscaling - CPU threshold (in percent, Horizontal Pod Autoscaler)
  cpu:
    threshold: 80
  # -- Autoscaling - RAM threshold (in percent, Horizontal Pod Autoscaler)
  memory:
    threshold: 80
  # -- Autoscaling - RPS threshold (in percent, Horizontal Pod Autoscaler)
  rps:
    threshold: 80

# Service
service:
  # -- Service - Annotation `networking.gke.io/max-rate-per-endpoint` (RPS per pod)
  max_rate_per_endpoint: 10

# Logging
logging:
  # -- Logging - Enabled (`true` or `false`)
  enabled: true
  # -- Logging - Sample rate (from 0 to 500000 / 1000000)
  sample_rate: 1000000

# ConfigMap
configMap:
  # -- Charge - Wallet phone number
  charge_wallet_phone_number: ""
  # -- Charge - Base URL
  charge_base_url: ""
  # -- Job sleep (ms)
  job_sleep_ms: ""
  # -- Unmarshal - Base URL
  unmarshal_base_url: ""
  # -- Alchemy - Base URL
  alchemy_base_url: ""
  # -- Ethereum - Payments network name
  ethereum_payments_network_name: ""

# Secrets (through environment variables)
secrets:
  # -- MongoDB Atlas URI (mongodb://username:password@hostname:port/database?params)
  mongo_uri: ""
  # -- Charge - Public key
  charge_public_key: ""
  # -- Charge - Secret key
  charge_secret_key: ""
  # -- Charge - Webhook ID
  charge_webhook_id: ""
  # -- Unmarshal - Auth key
  unmarshal_auth_key: ""
  # -- Charge - Payments Ethereum mnemonic
  charge_payments_ethereum_mnemonic: ""
  # -- Alchemy - Webhook ID
  alchemy_webhook_id: ""
  # -- Alchemy - Auth key
  alchemy_auth_key: ""
