# Default values for accounts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global
global:
  # -- Label 'environment'
  environment: ""

  # -- Google Cloud - Project ID
  project_id: ""
  # -- Google Cloud - Region
  region: ""

  # -- DNS domain
  domain: ""

  # Image
  image:
    # -- Repository ID
    repository: ""
    # -- Tag; overrides the image tag whose default is the chart appVersion.
    tag: ""

# Resources
resources:
  # -- Resources - Requests
  requests:
    cpu: ""
    memory: ""
  # -- Resources - Limits
  limits:
    cpu: ""
    memory: ""


# Autoscaling
autoscaling:
  # -- Autoscaling - Minimal replicas value (Horizontal Pod Autoscaler)
  min_replicas: 1
  # -- Autoscaling - Maximum replicas value (Horizontal Pod Autoscaler)
  max_replicas: 5
  # -- Autoscaling - CPU threshold (in percent, Horizontal Pod Autoscaler)
  cpu:
    threshold: 80
  # -- Autoscaling - RAM threshold (in percent, Horizontal Pod Autoscaler)
  memory:
    threshold: 80
  # -- Autoscaling - RPS threshold (in percent, Horizontal Pod Autoscaler)
  rps:
    threshold: 80

# Service
service:
  # -- Service - Annotation `networking.gke.io/max-rate-per-endpoint` (RPS per pod)
  max_rate_per_endpoint: 10

# Logging
logging:
  # -- Logging - Enabled (`true` or `false`)
  enabled: true
  # -- Logging - Sample rate (from 0 to 500000 / 1000000)
  sample_rate: 1000000

# ConfigMap
configMap:
  # -- Auth0 issuer URL
  auth0_issuer_url: ""
  # -- Auth0 audience
  auth0_audience: ""
  # -- Bundler - Paymaster Sandbox contract address
  paymaster_sandbox_contract_address_v_0_1_0: ""
  # -- Bundler - Paymaster Production contract address
  paymaster_production_contract_address_v_0_1_0: ""
  # -- Bundler - Entrypoint Sandbox contract address
  entrypoint_sandbox_contract_address_v_0_1_0: ""
  # -- Bundler - Entrypoint Production contract address
  entrypoint_production_contract_address_v_0_1_0: ""

# Secrets (through environment variables)
secrets:
  # -- MongoDB Atlas URI (mongodb://username:password@hostname:port/database?params)
  mongo_uri: ""
