apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    environment: {{ .Values.global.environment }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: {{ .Values.service.max_rate_per_endpoint }}
spec:
  selector:
    app: api
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: tcp
      protocol: TCP
      port: 8876
      targetPort: 8876
  type: ClusterIP
