apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    environment: {{ .Values.global.environment }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
      {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  selector:
    app: api
    environment: {{ .Values.global.environment }}
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: tcp
      protocol: TCP
      port: 8876
      targetPort: 8876
  type: ClusterIP
