apiVersion: v1
kind: ConfigMap
metadata:
  name: skandha
  namespace: {{ .Release.Namespace }}
  labels:
    app: skandha
    environment: {{ .Values.global.environment }}
data:
  skandha_networks: {{ .Values.configMap.skandha_networks | quote }}
  skandha_fuse_sparknet_estimation_static_buffer: {{ .Values.configMap.skandha_fuse_sparknet_estimation_static_buffer | quote }}
  skandha_fuse_estimation_static_buffer: {{ .Values.configMap.skandha_fuse_estimation_static_buffer | quote }}
  skandha_fuse_ban_slack: {{ .Values.configMap.skandha_fuse_ban_slack | quote }}
  skandha_fuse_sparknet_ban_slack: {{ .Values.configMap.skandha_fuse_sparknet_ban_slack | quote }}
  skandha_fuse_throttling_slack: {{ .Values.configMap.skandha_fuse_throttling_slack | quote }}
  skandha_fuse_sparknet_throttling_slack: {{ .Values.configMap.skandha_fuse_sparknet_throttling_slack | quote }}
  skandha_fuse_min_inclusion_denominator: {{ .Values.configMap.skandha_fuse_min_inclusion_denominator | quote }}
  skandha_fuse_sparknet_min_inclusion_denominator: {{ .Values.configMap.skandha_fuse_sparknet_min_inclusion_denominator | quote }}
