apiVersion: v1
kind: Service
metadata:
  name: skandha
  namespace: {{ .Release.Namespace }}
  labels:
    app: skandha
    environment: {{ .Values.global.environment }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: {{ .Values.service.max_rate_per_endpoint }}
spec:
  selector:
    app: skandha
    environment: {{ .Values.global.environment }}
  ports:
    - protocol: TCP
      port: 14337
      targetPort: 14337
  type: ClusterIP
