apiVersion: v1
kind: Service
metadata:
  name: skandha
  namespace: {{ .Release.Namespace }}
  labels:
    app: skandha
    environment: {{ .Values.global.environment }}
spec:
  selector:
    app: skandha
    environment: {{ .Values.global.environment }}
  ports:
    - protocol: TCP
      port: 14337
      targetPort: 14337
  type: ClusterIP
