apiVersion: v1
kind: Secret
metadata:
  name: relay
  namespace: {{ .Release.Namespace }}
  labels:
    app: relay
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  relay_secret: {{ .Values.secrets.relay_secret | b64enc }}
