apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
  labels:
    app: accounts
    environment: {{ .Values.global.environment }}
spec:
  default:
    logging:
      enabled: {{ .Values.logging.enabled }}
      sampleRate: {{ .Values.logging.sample_rate }}
  targetRef:
    group: ""
    kind: Service
    name: accounts
