apiVersion: v1
kind: Secret
metadata:
  name: accounts
  namespace: {{ .Release.Namespace }}
  labels:
    app: accounts
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
