apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: network
  namespace: {{ .Release.Namespace }}
  labels:
    app: network
    environment: {{ .Values.global.environment }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: network
  resourcePolicy:
    containerPolicies:
    - containerName: network
      controlledResources: ["cpu", "memory"]
      maxAllowed:
        cpu: {{ .Values.autoscaling.max_allowed.cpu }}
        memory: {{ .Values.autoscaling.max_allowed.memory }}
      minAllowed:
        cpu: {{ .Values.autoscaling.min_allowed.cpu }}
        memory: {{ .Values.autoscaling.min_allowed.memory }}
  updatePolicy:
    updateMode: "Auto"
