apiVersion: v1
kind: Secret
metadata:
  name: smart-wallets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  smart_wallets_jwt_secret: {{ .Values.secrets.smart_wallets_jwt_secret | b64enc }}
  fuse_wallet_backend_jwt: {{ .Values.secrets.fuse_wallet_backend_jwt | b64enc }}
  centrifugo_jwt: {{ .Values.secrets.centrifugo_jwt | b64enc }}
  centrifugo_api_key: {{ .Values.secrets.centrifugo_api_key | b64enc }}
  incoming_token_transfers_webhook_id: {{ .Values.secrets.incoming_token_transfers_webhook_id | b64enc }}
  charge_public_key: {{ .Values.secrets.charge_public_key | b64enc }}
  charge_secret_key: {{ .Values.secrets.charge_secret_key | b64enc }}
